services:
  clamd:
    build:
      context: clamav
      dockerfile: Dockerfile
    ports:
      - "3310:3310"
    volumes:
      - signatures:/var/lib/clamav
  freshclam:
    build:
      context: freshclam
      dockerfile: Dockerfile
    # environment:
    #   - FRESHCLAM_INTERVAL=60
    volumes:
      - signatures:/var/lib/clamav
    depends_on:
      - clamd
  minio:
    image: minio/minio
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=miniominio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/opt
      - minio-data:/data
    command: ["server", "/data", "--console-address", ":9001"]
  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set minioio http://minio:9000 minio miniominio;
      mc mb --ignore-existing minioio/test;
      exit 0;"
  elasticmq:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"
    volumes:
      - type: bind
        source: ./elasticmq/conf.d/custom.conf
        target: /opt/elasticmq.conf
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    user: root
    volumes:
      - $PWD/dynamodb/data:/data
  dynamodb-admin:
    container_name: dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
volumes:
  signatures:
  minio-data: